version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # location of your workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "maven"
    directory: "/" # or the subdir where your pom.xml lives
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10