@base_url = http://localhost:8089
@api = {{base_url}}/api/v1
@username = alice.johnson@example.com
@passowrd = password
@token = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcHBzIiwic3ViIjoiYm9iLnNtaXRoQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5MzY2MjU0LCJ1c2VyX2lkIjoyLCJpYXQiOjE3NDkzNjYyMzQsInNjb3BlIjoiIn0.FBStVWnq6h45QVXN7oJA6wxLRDW0OoRCWkxUBstP4PfzKJ81UVJzFt8s5N5dEu1dKc5vd66lOIvDw9d6QfGs2DMNf3LYH53X9r1zhNi0fIsShYSWnrCNahYi7zaRmaGys4cUMBehNj4VQGF-fbxW3UdCgbGxsDlPvJviz76Nfo7TyVZlV9ccVJd1mKJHm0E06H_FK8qab_Rq40jLMMt8B5OM3qdNLN_j6fGds-xXclIsT_W-EaNecfhCcDJ_lkqxsJ-sEIrtpiEp4MD1SqMzbXsyoXKKu6gHzwEeGpI6_giQrdCLf2wFEKBhzPeH-9hKGj8afjw8UWTVXXE4zV8HnA
@refresh = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcHBzIiwic3ViIjoiYW5kcmlhd2FuIiwiZXhwIjoxNzQ5MjY1MTgyLCJpYXQiOjE3NDkyNjUwNjIsInNjb3BlIjoiIn0.SVX9hYqVBs4b-7yPUZkBOXSRyGN7n7AW2A5XsMdJws40UBJvpBzztl2ir7L7C8A1FvjOQ59Mz5rAGgXH9xytPwXhRF8KHIXZF_aUO--cYhbjleFPjA1J_Y0QtI5ncEoLz6wMHDuz04_xjvbHaejSVo1dgbcZsq3iYc3UrL_Rgz-CQiwARk8CsOeevAGukxz_px-IMYPA2BIypWHcdbsqkgzcjTMAY0xBjGTEND97p1omvPPIDkT-pln8k3zyUEjY9qeEUT1AJwDB_HgoXePTSeW08oVZvrcWeOSdiEP3q9iuIVo93LjVOApcHJyGWzjEqYe_h1mrm2ciQ541BbzsTQ
GET {{api}}/users
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{api}}/me
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{api}}/auth/login
Accept: application/json
Authorization: Basic {{username}}:{{passowrd}}

###

POST {{api}}/auth/token/refresh
Accept: application/json
Authorization: Bearer {{refresh}}

