@base_url = http://localhost:8089
@api = {{base_url}}/api/v1
@username = alice.johnson@example.com
@passowrd = password
@token = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcHBzIiwic3ViIjoiYWxpY2Uuam9obnNvbkBleGFtcGxlLmNvbSIsImV4cCI6MTc1MDYwODgxMCwidXNlcl9pZCI6MSwiaWF0IjoxNzUwNjA4NjkwLCJzY29wZSI6IiJ9.BcO7eTXIjx0pQt4kYZdnB2ffy4oOsveDzpo-troM6wDKOqnkMh3E_QfLa7o3BObJP3C2ZLswypryt6bhi7PNXVSV08jJ43NMkQXFf38NYfld91a1VPxRm5-EnVvK9PI239VWftQXfGrGsnMjHWn239J_WiRqLVf5onFuIovxPb8xunSf3lfxM_Jaz0VQbmBtGT6iX9YNvTo8VpiHJLEeKRj6vYf_JI2bzdVH977hXBTxSQhvhkOlnpOa8AQBvQFbA0pbjnGXSfazPEnTTLxojdH2NMb9xXrDpTOx7hE3GLvrKodL2rwwdAeqUh_TjkdFmJooNwT82lifggCKk3_kDQ
@refresh = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhcHBzIiwic3ViIjoiYWxpY2Uuam9obnNvbkBleGFtcGxlLmNvbSIsImV4cCI6MTc0OTM4NzY5OCwidXNlcl9pZCI6MSwiaWF0IjoxNzQ5Mzg3NTc4LCJzY29wZSI6IiJ9.iqcexuIGb8m-Z6mUKzRHsksl3GTQoc6wamQGlJhDB-hAiU7YrgJmKdLA4aD3XNbRTi6aiaGS0R5N5GCBh-_O81sFywa_stNgJUEA-o-SnTeBdaJsD1ITPPzu9xivyDR6vhz6LrW1mukwm4mCcR15R-5w0gIU1nl5XhBX3Rggfjr-lnrqEItkWglKtY1haJ_Aemc9EmoCxwSsLZ_OEbKdkzyCxcYcJ_5IvHeU98Z_DzhmnxyFBQXUFYTbENA162P3YL99dGLWSNBQ30akUYacjYT3aF4zif1qAH8M42tgb-OKt9DXlKWsyojyAvH2qQWT8eu5o4uxs1L8Gw5PuQk-JA
GET {{api}}/users
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{api}}/me
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{api}}/auth/login
Accept: application/json
Authorization: Basic {{username}}:{{passowrd}}

###

POST {{api}}/auth/token/refresh
Accept: application/json
Content-Type: application/json

{
    "token": "{{refresh}}"
}

###

GET {{base_url}}/actuator
Accept: application/json
Content-Type: application/json

