name: CI/CD Test, Formatting and Collect Coverage

on:
  pull_request:
    branches: [main]

env:
  CERTS_PATH: './src/main/resources/certs'

jobs:
  run:
    name: Run Tests, Formatting and Collect Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy Private and Public Keys
        run: |
          echo "${{ secrets.SAMPLE_PRIVATE_KEY }}" > ${CERTS_PATH}/private_key.pem
          echo "${{ secrets.SAMPLE_PUBLIC_KEY }}" > ${CERTS_PATH}/public_key.pem
          chmod 600 ${CERTS_PATH}/private_key.pem ${CERTS_PATH}/public_key.pem
          tree ${CERTS_PATH}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Run tests and collect coverage
        run: mvn -B clean test jacoco:report
      - name: Upload coverage to Codecov
        if: false
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Run Spotless and apply formatting
        run: mvn spotless:apply
      - name: Commit and push changes if formatting was applied
        env:
          GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_NAME: ${{ github.actor }}"
        run: |
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(format): apply Spotless auto-format"
            git push
          else
            echo "No formatting changes to commit."
          fi