name: CI/CD Test, Formatting and Collect Coverage

on:
  pull_request:
    branches: [main]

env:
  CERTS_PATH: './src/main/resources/certs'

jobs:
  run:
    name: Run Tests, Formatting and Collect Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Spotless check
        run: mvn spotless:check
      - name: Generate Private and Public Keys
        run: |
          mkdir -p ${CERTS_PATH}
          openssl genpkey -algorithm RSA -out ${CERTS_PATH}/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in ${CERTS_PATH}/private_key.pem -out ${CERTS_PATH}/public_key.pem
          chmod 600 ${CERTS_PATH}/private_key.pem ${CERTS_PATH}/public_key.pem
          tree ${CERTS_PATH}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Run tests and collect coverage
        run: mvn -B clean test jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}